### ISSUE TITLE
ImportError: No module named site

### ISSUE THREAD

**Issue by mansdell** [radio-astro-tools/casa-python#18]
I am trying to install casa-py (MacOS 10.12.6 Sierra, CASA 5.1.1), but when I run "casa-python setup.py install" from the command line, I get the following output and ImportError:

Determined Python version in CASA... b'2.7'
Creating casa-python script...
Downloading setuptools...
Installing setuptools...
x setuptools-3.4.3/
x setuptools-3.4.3/CHANGES (links).txt
x setuptools-3.4.3/CHANGES.txt
x setuptools-3.4.3/DEVGUIDE.txt
x setuptools-3.4.3/docs/
x setuptools-3.4.3/docs/conf.py
x setuptools-3.4.3/docs/development.txt
x setuptools-3.4.3/docs/easy_install.txt
x setuptools-3.4.3/docs/formats.txt
x setuptools-3.4.3/docs/index.txt
x setuptools-3.4.3/docs/Makefile
x setuptools-3.4.3/docs/merge-faq.txt
x setuptools-3.4.3/docs/merge.txt
x setuptools-3.4.3/docs/pkg_resources.txt
x setuptools-3.4.3/docs/python3.txt
x setuptools-3.4.3/docs/releases.txt
x setuptools-3.4.3/docs/roadmap.txt
x setuptools-3.4.3/docs/setuptools.txt
x setuptools-3.4.3/docs/using.txt
x setuptools-3.4.3/docs/_templates/
x setuptools-3.4.3/docs/_templates/indexsidebar.html
x setuptools-3.4.3/docs/_theme/
x setuptools-3.4.3/docs/_theme/nature/
x setuptools-3.4.3/docs/_theme/nature/static/
x setuptools-3.4.3/docs/_theme/nature/static/nature.css_t
x setuptools-3.4.3/docs/_theme/nature/static/pygments.css
x setuptools-3.4.3/docs/_theme/nature/theme.conf
x setuptools-3.4.3/easy_install.py
x setuptools-3.4.3/ez_setup.py
x setuptools-3.4.3/launcher.c
x setuptools-3.4.3/MANIFEST.in
x setuptools-3.4.3/PKG-INFO
x setuptools-3.4.3/pkg_resources.py
x setuptools-3.4.3/README.txt
x setuptools-3.4.3/release.py
x setuptools-3.4.3/setup.cfg
x setuptools-3.4.3/setup.py
x setuptools-3.4.3/setuptools/
x setuptools-3.4.3/setuptools/archive_util.py
x setuptools-3.4.3/setuptools/cli-32.exe
x setuptools-3.4.3/setuptools/cli-64.exe
x setuptools-3.4.3/setuptools/cli-arm-32.exe
x setuptools-3.4.3/setuptools/cli.exe
x setuptools-3.4.3/setuptools/command/
x setuptools-3.4.3/setuptools/command/alias.py
x setuptools-3.4.3/setuptools/command/bdist_egg.py
x setuptools-3.4.3/setuptools/command/bdist_rpm.py
x setuptools-3.4.3/setuptools/command/bdist_wininst.py
x setuptools-3.4.3/setuptools/command/build_ext.py
x setuptools-3.4.3/setuptools/command/build_py.py
x setuptools-3.4.3/setuptools/command/develop.py
x setuptools-3.4.3/setuptools/command/easy_install.py
x setuptools-3.4.3/setuptools/command/egg_info.py
x setuptools-3.4.3/setuptools/command/install.py
x setuptools-3.4.3/setuptools/command/install_egg_info.py
x setuptools-3.4.3/setuptools/command/install_lib.py
x setuptools-3.4.3/setuptools/command/install_scripts.py
x setuptools-3.4.3/setuptools/command/launcher manifest.xml
x setuptools-3.4.3/setuptools/command/register.py
x setuptools-3.4.3/setuptools/command/rotate.py
x setuptools-3.4.3/setuptools/command/saveopts.py
x setuptools-3.4.3/setuptools/command/sdist.py
x setuptools-3.4.3/setuptools/command/setopt.py
x setuptools-3.4.3/setuptools/command/test.py
x setuptools-3.4.3/setuptools/command/upload_docs.py
x setuptools-3.4.3/setuptools/command/__init__.py
x setuptools-3.4.3/setuptools/compat.py
x setuptools-3.4.3/setuptools/depends.py
x setuptools-3.4.3/setuptools/dist.py
x setuptools-3.4.3/setuptools/extension.py
x setuptools-3.4.3/setuptools/gui-32.exe
x setuptools-3.4.3/setuptools/gui-64.exe
x setuptools-3.4.3/setuptools/gui-arm-32.exe
x setuptools-3.4.3/setuptools/gui.exe
x setuptools-3.4.3/setuptools/lib2to3_ex.py
x setuptools-3.4.3/setuptools/package_index.py
x setuptools-3.4.3/setuptools/py26compat.py
x setuptools-3.4.3/setuptools/py27compat.py
x setuptools-3.4.3/setuptools/py31compat.py
x setuptools-3.4.3/setuptools/sandbox.py
x setuptools-3.4.3/setuptools/script template (dev).py
x setuptools-3.4.3/setuptools/script template.py
x setuptools-3.4.3/setuptools/site-patch.py
x setuptools-3.4.3/setuptools/ssl_support.py
x setuptools-3.4.3/setuptools/svn_utils.py
x setuptools-3.4.3/setuptools/tests/
x setuptools-3.4.3/setuptools/tests/doctest.py
x setuptools-3.4.3/setuptools/tests/entries-v10
x setuptools-3.4.3/setuptools/tests/environment.py
x setuptools-3.4.3/setuptools/tests/indexes/
x setuptools-3.4.3/setuptools/tests/indexes/test_links_priority/
x setuptools-3.4.3/setuptools/tests/indexes/test_links_priority/external.html
x setuptools-3.4.3/setuptools/tests/indexes/test_links_priority/simple/
x setuptools-3.4.3/setuptools/tests/indexes/test_links_priority/simple/foobar/
x setuptools-3.4.3/setuptools/tests/indexes/test_links_priority/simple/foobar/index.html
x setuptools-3.4.3/setuptools/tests/py26compat.py
x setuptools-3.4.3/setuptools/tests/script-with-bom.py
x setuptools-3.4.3/setuptools/tests/server.py
x setuptools-3.4.3/setuptools/tests/svn_data/
x setuptools-3.4.3/setuptools/tests/svn_data/dummy.zip
x setuptools-3.4.3/setuptools/tests/svn_data/dummy13.zip
x setuptools-3.4.3/setuptools/tests/svn_data/dummy14.zip
x setuptools-3.4.3/setuptools/tests/svn_data/dummy15.zip
x setuptools-3.4.3/setuptools/tests/svn_data/dummy16.zip
x setuptools-3.4.3/setuptools/tests/svn_data/dummy17.zip
x setuptools-3.4.3/setuptools/tests/svn_data/dummy18.zip
x setuptools-3.4.3/setuptools/tests/svn_data/svn13_example.zip
x setuptools-3.4.3/setuptools/tests/svn_data/svn13_ext_list.txt
x setuptools-3.4.3/setuptools/tests/svn_data/svn13_ext_list.xml
x setuptools-3.4.3/setuptools/tests/svn_data/svn13_info.xml
x setuptools-3.4.3/setuptools/tests/svn_data/svn14_example.zip
x setuptools-3.4.3/setuptools/tests/svn_data/svn14_ext_list.txt
x setuptools-3.4.3/setuptools/tests/svn_data/svn14_ext_list.xml
x setuptools-3.4.3/setuptools/tests/svn_data/svn14_info.xml
x setuptools-3.4.3/setuptools/tests/svn_data/svn15_example.zip
x setuptools-3.4.3/setuptools/tests/svn_data/svn15_ext_list.txt
x setuptools-3.4.3/setuptools/tests/svn_data/svn15_ext_list.xml
x setuptools-3.4.3/setuptools/tests/svn_data/svn15_info.xml
x setuptools-3.4.3/setuptools/tests/svn_data/svn16_example.zip
x setuptools-3.4.3/setuptools/tests/svn_data/svn16_ext_list.txt
x setuptools-3.4.3/setuptools/tests/svn_data/svn16_ext_list.xml
x setuptools-3.4.3/setuptools/tests/svn_data/svn16_info.xml
x setuptools-3.4.3/setuptools/tests/svn_data/svn17_example.zip
x setuptools-3.4.3/setuptools/tests/svn_data/svn17_ext_list.txt
x setuptools-3.4.3/setuptools/tests/svn_data/svn17_ext_list.xml
x setuptools-3.4.3/setuptools/tests/svn_data/svn17_info.xml
x setuptools-3.4.3/setuptools/tests/svn_data/svn18_example.zip
x setuptools-3.4.3/setuptools/tests/svn_data/svn18_ext_list.txt
x setuptools-3.4.3/setuptools/tests/svn_data/svn18_ext_list.xml
x setuptools-3.4.3/setuptools/tests/svn_data/svn18_info.xml
x setuptools-3.4.3/setuptools/tests/test_bdist_egg.py
x setuptools-3.4.3/setuptools/tests/test_build_ext.py
x setuptools-3.4.3/setuptools/tests/test_develop.py
x setuptools-3.4.3/setuptools/tests/test_dist_info.py
x setuptools-3.4.3/setuptools/tests/test_easy_install.py
x setuptools-3.4.3/setuptools/tests/test_egg_info.py
x setuptools-3.4.3/setuptools/tests/test_find_packages.py
x setuptools-3.4.3/setuptools/tests/test_markerlib.py
x setuptools-3.4.3/setuptools/tests/test_packageindex.py
x setuptools-3.4.3/setuptools/tests/test_resources.py
x setuptools-3.4.3/setuptools/tests/test_sandbox.py
x setuptools-3.4.3/setuptools/tests/test_sdist.py
x setuptools-3.4.3/setuptools/tests/test_svn.py
x setuptools-3.4.3/setuptools/tests/test_test.py
x setuptools-3.4.3/setuptools/tests/test_upload_docs.py
x setuptools-3.4.3/setuptools/tests/win_script_wrapper.txt
x setuptools-3.4.3/setuptools/tests/__init__.py
x setuptools-3.4.3/setuptools/version.py
x setuptools-3.4.3/setuptools/__init__.py
x setuptools-3.4.3/setuptools.egg-info/
x setuptools-3.4.3/setuptools.egg-info/dependency_links.txt
x setuptools-3.4.3/setuptools.egg-info/entry_points.txt
x setuptools-3.4.3/setuptools.egg-info/PKG-INFO
x setuptools-3.4.3/setuptools.egg-info/requires.txt
x setuptools-3.4.3/setuptools.egg-info/SOURCES.txt
x setuptools-3.4.3/setuptools.egg-info/top_level.txt
x setuptools-3.4.3/setuptools.egg-info/zip-safe
x setuptools-3.4.3/tests/
x setuptools-3.4.3/tests/api_tests.txt
x setuptools-3.4.3/tests/manual_test.py
x setuptools-3.4.3/tests/shlib_test/
x setuptools-3.4.3/tests/shlib_test/hello.c
x setuptools-3.4.3/tests/shlib_test/hello.pyx
x setuptools-3.4.3/tests/shlib_test/hellolib.c
x setuptools-3.4.3/tests/shlib_test/setup.py
x setuptools-3.4.3/tests/shlib_test/test_hello.py
x setuptools-3.4.3/tests/test_pkg_resources.py
x setuptools-3.4.3/_markerlib/
x setuptools-3.4.3/_markerlib/markers.py
x setuptools-3.4.3/_markerlib/__init__.py
ImportError: No module named site
Traceback (most recent call last):
  File "setup_casapy_pip.py", line 277, in <module>
    url=SETUPTOOLS_URL, md5_checksum=SETUPTOOLS_MD5)
  File "setup_casapy_pip.py", line 142, in install_package
    raise SystemError("{0} installation failed!".format(packagename))
SystemError: setuptools installation failed!

**Comment by mansdell** [comment]
I figured out the problem. In Python 3, the "python_version" returned by "get_python_version_mac" is a byte, not a string, so it actually returns b'2.7' (rather than just '2.7'). In Python 2, the byte is ignored and the string is returned. This is propagated throughout the code, so that the paths written out in the executable files include the 'b' before the version number. This means that the paths to the modules cannot be found because they do not exist. 

I fixed this in "setup_casapy_pip.py" by adding the line "version = version.decode("utf-8")"  at the end of the "get_python_version_mac()" function (this converts a byte to a string and thus drops the 'b' in front of the version number). This allowed me to run the setup script successfully, however I'm still getting ImportError failures when running, for example, "casa-pip install astropy"

**Comment by mansdell** [comment]
I found the source of the remaining import error failures. The pip version installed by "setup_casapy_pip.py" is very old, so I updated the PIP_URL and PIP_MD5 values to those for the latest version of pip, found [here](https://pypi.python.org/pypi/pip/9.0.1). Everything seems to work fine now.

**Comment by keflavich** [comment]
Nice work tracking down the error.  Would you be willing to submit a pull request with the fix?
